title: "Machine Learning for the Geosciences: Winter 2026"
description: Course materials for the Winter 2026 iteration of ESS 469/569.
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
header_pages:
  - index.md
  - syllabus.md
  - assignments/index.md
