baseURL = 'https://uw-mlgeo.github.io/MLGEO-2026/'
languageCode = 'en-us'
title = "Machine Learning for the Geosciences: Winter 2026"
description = Course materials for the Winter 2026 iteration of ESS 469/569.
theme = 'hugo-tufte'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
