baseURL = 'https://uw-mlgeo.github.io/MLGEO-2026/'
languageCode = 'en-us'
title = "Machine Learning for the Geosciences"
theme = "no-style-please"

[params]
  [params.theme_config]
    back_home_text = "Machine learning for the geosciences"
    isListGroupByDate = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'