baseURL = 'https://uw-mlgeo.github.io/MLGEO-2026/'
languageCode = 'en-us'
title = "Machine Learning for the Geosciences: Winter 2026"
description = "Course materials for the Winter 2026 iteration of ESS 469/569."
theme = "archie"

[[menus.nav]]
  name = "Home"
  url = "/"
  weight = 1

[[menus.nav]]
  name = "Syllabus"
  url = "/syllabus/"
  weight = 2

[[menus.nav]]
  name = "Assignments"
  url = "/assignments/"
  weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
